## Random

In [1]:
import numpy as np

rand

In [2]:
# Building random arrays range(0 to 1)   # uniform distribution

np.random.rand(4)

array([0.11092638, 0.40152504, 0.75290035, 0.52778933])

In [3]:
np.random.rand(4,4)

array([[0.21781072, 0.08628708, 0.42534224, 0.5809005 ],
       [0.41569566, 0.5872772 , 0.6167373 , 0.83597226],
       [0.75622806, 0.43129824, 0.25882077, 0.56526598],
       [0.67593273, 0.78144688, 0.7922765 , 0.72367053]])

randn

In [5]:
# Return a sample (or samples) from the "standard normal" 
# distribution. Unlike rand which is uniform:

np.random.randn(4)

array([ 0.38903709, -1.28973703,  0.6040476 , -0.25563441])

In [6]:
np.random.randn(4,4)

array([[-0.34044321, -0.53343459,  0.484037  ,  0.89794171],
       [ 0.21673692, -1.29150808, -0.16440835,  0.69790702],
       [ 1.14491764,  0.06531084, -0.29802124,  0.41425276],
       [ 1.193305  , -0.6780461 ,  1.47409126, -1.64433151]])

randint

In [9]:
# Return random integers (จำนวนเต็ม) from low (inclusive) to high (exclusive).

np.random.randint(1,50) #(low, high, number of member default = 1)

22

In [10]:
np.random.randint(1,50,10)#(low, high, number of member default = 1)

array([42,  6,  5, 41, 36, 26, 11, 47, 37, 28])