In [1]:
import numpy as np

In [15]:
arr = np.arange(15)
arr1 = np.random.randint(0,30,10)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
arr1

array([26,  2, 13, 18,  8, 29, 18, 21, 11, 19])

### Reshape

In [7]:
arr.reshape(5,3)  #(Rows, Columns)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

max,min,argmax,argmin

In [17]:
# methods ที่ใช่สำหรับหาค่า max หรือ min พร้อมด้วย index locations (เลขตำแหน่งของสมาชิกใน array) ด้วย argmin หรือ argmax

arr1.max()

29

In [18]:
arr1.min()

2

In [19]:
arr1.argmax()

5

In [20]:
arr1.argmin()

1

### Shape

In [21]:
# Shape คือ attribute ของ arrays (ไม่ใช่ method):

arr.shape

(15,)

In [23]:
# Notice the two sets of brackets
arr.reshape(1,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [24]:
arr.reshape(1,15).shape

(1, 15)

In [25]:
arr.reshape(15,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [26]:
arr.reshape(15,1).shape

(15, 1)

dtype

In [ ]:
#คำสั่งในการตรวจดู the data type ของ object ใน array:

In [27]:
arr.dtype

dtype('int32')